 name: Build docker image, push to ACR 

 on:
   push:
     branches:
       - main
   workflow_dispatch:

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       - name: Log in to container registry
         uses: docker/login-action@v2
         with:
           registry: libraryacr.azurecr.io
           username: ${{ secrets.registryUsernameVepatel }}
           password: ${{ secrets.registryPasswordVepatel  }}


       - name: Build and push container image to registry
         uses: docker/build-push-action@v3
         with:
           context: .
           push: true
           tags: 
            libraryacr.azurecr.io/library_web:latest
            libraryacr.azurecr.io/library_web:${{ env.DATE_TAG }} # Date tag
           file: ./Dockerfile
