# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - library-backend-api

on:
  push:
    branches:
      - Production
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
    
jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment:
      name: 'production'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # - name: 'Login to ACR using SP'
    #   uses: azure/docker-login@v2
    #   with:
    #      login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_SPID_LibraryPROD }}
    #      username: ${{ secrets.REGISTRY_USERNAME_SPID_LibraryPROD }}
    #      password: ${{ secrets.REGISTRY_PASSWORD_SPID_LibraryPROD }}

    - name: 'Login to ACR using UAMI'
      uses: azure/login@v2
      with:
         client-id: ${{ secrets.UAMI_CLIENT_ID }}
         tenant-id: ${{ secrets.UAMI_TENANT_ID }}
         subscription-id: ${{ secrets.UAMI_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: |
        az acr login --name libraryprod

    - name: Build and push container image to registry
      run: |
        docker build -t libraryprod.azurecr.io/library-fronend:${{ github.sha }} .
        docker push libraryprod.azurecr.io/library-frontend:${{ github.sha }}

    
    # - name: Build and push container image to registry
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: libraryprod.azurecr.io/library-backend:${{ github.sha }}
    #     file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.UAMI_CLIENT_ID }}
        tenant-id: ${{ secrets.UAMI_TENANT_ID }}
        subscription-id: ${{ secrets.UAMI_SUBSCRIPTION_ID }}
          
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'library-fronend-web'
        slot-name: 'production'
        images: 'libraryprod.azurecr.io/library-fronend:${{ github.sha }}'
